### ISSUE TITLE
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by santoshgistto** [yoonic/atlas#11]
bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

**Comment by andrecrt** [comment]
Which Node version are you using? 4LTS?

**Comment by santoshgistto** [comment]
node version : v7.4.0 
 ubuntu : 14LTS

**Comment by andrecrt** [comment]
Can you try with Node.js v4? You can use [nvm](https://github.com/creationix/nvm) to have multiple Node versions in your machine

**Comment by phoenixvk** [comment]
try
npm install bcrypt@0.8.7
npm install node-sass@3.5.3

**Comment by phoenixvk** [comment]
and lemme know

**Comment by santoshgistto** [comment]
@phoenixvk still facing same issue !

**Comment by andrecrt** [comment]
Have you tried using Node.js v4?

**Comment by santoshgistto** [comment]
@andreftavares  thank you  got fixed by changing the  Node version to v4.4.2

**Comment by santoshgistto** [comment]
@andreftavares  yes
