### ISSUE TITLE
Design Style which you are following?

### ISSUE THREAD

**Issue by iraycd** [yoonic/atlas#13]
Which design style are you following?

**Comment by andrecrt** [comment]
Thanks for your interest, but please do not open issues to ask questions :)

I don't follow any particular style, but try to have things as decoupled as possible.

**Comment by iraycd** [comment]
@andreftavares I won't open them any issue for asking a question anymore.

**Comment by andrecrt** [comment]
If you have any question you can email me at andre [ at ] yoonic [ dot ] net
