### ISSUE TITLE
Can't upload images

### ISSUE THREAD

**Issue by mateomorrison** [yoonic/atlas#15]
It's not clear where to update to get your images uploaded after going for your own atlas, rethinkdb and nicistore on a VPS.

I think there is something related to [here](https://github.com/yoonic/atlas/blob/master/src/resources/products/scripts/uploadImages.js)

@andreftavares How to upload images to your products?

I will refer some issues I am encountering for both NICI and Atlas. 

# Currency
I am currently going to handle DOP (Dominican Pesos), where there is no cents and the format is:  `RD$`. For example: `RD$100` or `RD$10,000`. The questions are the following:

- How to create a currency, there is just EUR and USD on the app.
- Stripe supports DOP. Nicistore does?

# Language

I am going to translate (and providing you guys the rep for it 👍 ) Nicistore to Spanish. I need to delete `en {` and `pt {`. Or you just add `es {` in handlers? And where 

# Marketplace

We're developing and improving Nicistore to become it a multi-vendor marketplace too. Which files should the developer focus when creating the module. This will be a non admin, that can create products. For now we will not focus on Dashboard for them bla bla. 

**Simple as:**

Register to Sell > Add products > We receive request > We accept or reject > They receive e-mail with their product's link.

# Social Login

Where we can integrate OpenID or Facebook, Twitter and Google Login?

# SMS Notifications

Where we can integrate with Twilio when someone creates account a two-factor auth and order is made. Since phone number **is already there**.

**Comment by mateomorrison** [comment]
When adding an image to a product, the whole machine gets crashed. Seems like it's set to upload it to nicistore's db and since we don't have access it just crash.

**Comment by andreftavares** [comment]
- https://github.com/yoonic/atlas/blob/master/src/resources/files/handlers.js#L25

**Comment by andrecrt** [comment]
No, it is not set to upload to nicistore's DB. See:

- https://github.com/yoonic/atlas/blob/master/src/resources/files/handlers.js#L25
- https://github.com/yoonic/atlas/blob/master/src/resources/files/utils.js#L17-L50
- https://github.com/yoonic/atlas/blob/master/config/development.js#L28-L32

**Comment by mateomorrison** [comment]
Why I can't upload images to products or banner?

**Comment by emadicio** [comment]
@mateomorrison What do you mean it crashes? Any useful log?
