### ISSUE TITLE
Integrating Paytm Payment Gateway

### ISSUE THREAD

**Issue by phoenixvk** [yoonic/atlas#16]
I'm integrating paytmgateway what I want to achieve is call genratechecksum() function. which gives me checksum and post the data to their URL.
I got checksum successfully now how should I post it where should I write the code? How to pass those parameters to Nicistore and again how to post the data to PAYTM url.

**Comment by phoenixvk** [comment]
This is not the issue. I just want to know how should I implement it.

**Comment by mateomorrison** [comment]
Look here and follow André's steps: [https://github.com/yoonic/atlas/issues/2#issuecomment-244927167](https://github.com/yoonic/atlas/issues/2#issuecomment-244927167)
