### ISSUE TITLE
Is this repository going to be maintained?

### ISSUE THREAD

**Issue by aboglioli** [yoonic/atlas#18]
Is it going to be updated or enhanced? Or is it going to have dependency updates at least?

**Comment by andrecrt** [comment]
Hi, please refer to the answer I give in https://github.com/yoonic/nicistore/issues/18#issuecomment-285337438 :)

Thanks for the interest on the project,
Best regards,
André.

**Comment by aboglioli** [comment]
Thanks! You are right.

We are working with this right now. When we have some improvements some PRs will be sent :+1: 

Regards.
