### ISSUE TITLE
Atlas is not running on docker digital ocean

### ISSUE THREAD

**Issue by phoenixvk** [yoonic/atlas#19]
Dear @andreftavares I have been working on this project since many days enhancing its components and usability. Please provide us document or guideline to run this project on docker either on digitalocean or on AWS. If this project is not running on docker then it will be obsolete. Please do us a favour. I found no one who have made it work. Please do us a favour. Thank you.

**Comment by phoenixvk** [comment]
I have successfully executed and put nicistore storefront in production. But I am having many issues with atlas.

**Comment by andrecrt** [comment]
Hi,

First of all thanks for your interest on the project. Unfortunately this is a pet project for which I don't have as much time as I wished... especially for support.

More, Docker is outside of the realm of this app and is specific to deploy and, as you know, there are numerous ways you can have an app deployed (even with Docker!). Despite that, both Nicistore and Atlas are provided with a Dockerfile which is what I use in production and, in the specific case of Atlas, the command that I run is:

```docker run -d --name {YOUR_CONTAINER_NAME} -e JWT_KEY={YOUR_KEY_HERE} -e MAILGUN_DOMAIN={YOUR_DOMAIN_HERE} -e MAILGUN_API_KEY={YOUR_KEY_HERE} -e SWITCH_ACCOUNT_ID={YOUR_ACCOUNT_ID_HERE} -e SWITCH_PRIVATE_KEY={YOUR_PRIVATE_KEY_HERE} -v {YOUR_SERVER_FOLDER_HERE}:/uploads --link {YOUR_RETHINKDB_CONTAINER_NAME_HERE}:db -p {THE_PORT_YOU_WANT_TO_RUN}:8000 -t {THE_DOCKER_IMAGE_TAG}```

What this does basically is set some environment variables (check the config files) and link to the RethinkDB container of the database. But again, this is just one way of doing it...
