### ISSUE TITLE
Atlas is not getting deployed on VPS using Dockerfile

### ISSUE THREAD

**Issue by coderminion** [yoonic/atlas#20]
Anyone got success expt. Author? Deploying Atlas on VPS on DigitalOcean? Please share if so. I can run nicistore on VPS but atlas is not running though I follwed deployment steps.

**Comment by andrecrt** [comment]
Deployment and Docker is something that is out of the scope of this repository. 

- The Live site nicistore.com is deployed using both Atlas and Nicistore's Dockerfiles.
- Both apps require some env variables to be setup when running a container (perhaps this is what's missing on your setup).
- I recommend reading both app's configs and look for which variables can be setup at runtime.
- The most tricky variable maybe the one related to RethinkDB which can be linked (https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/) to Atlas container, defining both `DB_PORT_28015_TCP_ADDR` and `DB_PORT_28015_TCP_PORT` that you can see on https://github.com/yoonic/atlas/blob/master/config/development.js

Finally, just a remark that you do **not** need Docker to deploy your app. A node.js app can be deployed in a numerous different ways.
