### ISSUE TITLE
Atlas with mongoDB

### ISSUE THREAD

**Issue by hoangtrongphuc** [yoonic/atlas#4]
How can I use mongodb instead of rethinkDB ?

**Comment by andrecrt** [comment]
@hoangtrongphuc hi!

The app was built around RethinkDB, so there isn't an ORM or abstraction layer where you could simply select a MongoDB "driver". However, the DB-related code is isolated enough that it should be fairly simple to port it to MongoDB. If I'm not mistaken or missing anything...
- https://github.com/yoonic/atlas/blob/master/src/core/db.js
- https://github.com/yoonic/atlas/blob/master/src/resources/carts/models.js
- https://github.com/yoonic/atlas/blob/master/src/resources/checkouts/models.js
- https://github.com/yoonic/atlas/blob/master/src/resources/collections/models.js
- https://github.com/yoonic/atlas/blob/master/src/resources/contents/models.js
- https://github.com/yoonic/atlas/blob/master/src/resources/orders/models.js
- https://github.com/yoonic/atlas/blob/master/src/resources/products/models.js
- https://github.com/yoonic/atlas/blob/master/src/resources/users/models.js
