### ISSUE TITLE
would you consider about horizonjs?

### ISSUE THREAD

**Issue by hbakhtiyor** [yoonic/atlas#5]

**Comment by andrecrt** [comment]
Hi, haven't looked at it properly... but given that it's from the RethinkDB team, should be awesome :)

Any particular reason you think it would be interesting to use it?

**Comment by hbakhtiyor** [comment]
hi, particularly will be less codes :)
also did you look at https://github.com/reactioncommerce/reaction? built with meteor

**Comment by andrecrt** [comment]
I didn't know Reaction, thank you for sharing! One major think that pops immediately when I saw it is the coupling between back and front-end. More (and this I'm not sure but...) from my limited knowledge of Meteor... I don't know if you have server-side render (essential for Search Engine Optimisation)
