### ISSUE TITLE
Ever tested new bcrypt/node-sass modules?

### ISSUE THREAD

**Issue by Redmega** [yoonic/atlas#8]
As per #1 you mentioned you would test the new bcrypt and node-sass modules in this and nicistore. Any update on that?

**Comment by Redmega** [comment]
Never mind, it was starting to be too much trouble to use the latest node. I used NVM to switch back to the 4.6.2 LTS.

**Comment by andrecrt** [comment]
Hi @Redmega ,

Thanks for your interest on the project.

Unfortunately, even though there is the ambition to update the project to latest versions of Node, Libraries, etc... that effort is still far away :/

NVM is a good solution and works well :)
